general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/abyss.toml"
]


[font]
size = 12.0

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[window]
opacity = 0.7
padding = { x = 5, y = 5 }

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]
